version: '3'
services:

  web:
    build: ./frontend/
    volumes:
    - ./frontend/:/app/
    - /app/node_modules
    - /root/.npm
    ports:
    - '3000:3000'
    environment:
    - NODE_ENV=development

  backend:
    build: api/
    ports: 
    - "8091:8091"
    links:
    - postgres
    depends_on:
    - postgres

  postgres:
    image: postgres
    environment:
      POSTGRES_PASSWORD: mysecretpassword
      POSTGRES_USER: postgres
      POSTGRES_DB: Aktivist_Db
    volumes:
    - db-data:/var/lib/postgresql/data
    ports:
    - "5432:5432"

  blockchain:
    image: docker.pkg.github.com/alxgrk/blockchain-hackathon-2019/blockchain:1.0.7
    #build: ./blockchain/
    ports:
    - "8080:8080"
    - "9876:9876"
    external_links:
    - peer0.org1.example.com:peer0
    - ca.org1.example.com:ca
    - orderer.example.com:orderer
    volumes:
    - ./blockchain/fabric-scripts/hlfv12/composer/crypto-config/:/hyperledger-fabric/crypto-config
    - ./blockchain/the-aktivist-network/lib/:/hyperledger-fabric/the-aktivist-network/lib
    - ./blockchain/the-aktivist-network/models/:/hyperledger-fabric/the-aktivist-network/models
    - network-admin-cards:/hyperledger-fabric/admin-cards/
    - /hyperledger-fabric/node_modules
    - /root/.npm

networks:
  default: 
    external:
     name: blockchain_hackathon

volumes:
  db-data:
  network-admin-cards:
