version: '3'
services:

  web:
    build: ./frontend/
    volumes:
    - ./frontend/:/app/
    - /app/node_modules
    - /root/.npm
    ports:
    - '3000:3000'
    environment:
    - NODE_ENV=development

  backend:
    build: api/
    ports: 
    - "8090:8090"
    depends_on:
    - postgres

  postgres:
    image: postgres
    volumes:
    - db-data:/var/lib/postgresql/data
    ports:
    - "5432:5432"

  blockchain:
    build: hyperledger-composer/
    ports:
    - "8080:8080"
    - "9876:9876"
    network_mode: host
    volumes:
    - ./hyperledger-composer/fabric-scripts/hlfv12/composer/crypto-config/:/hyperledger-fabric/crypto-config
    - network-admin-cards:/hyperledger-fabric/admin-cards/
    - /hyperledger-fabric/node_modules
    - /root/.npm
#    depends_on:
#    - ca.org1.example.com
#    - peer0.org1.example.com
#    - orderer.example.com
#    - couchdb 

  # copied from startFabric.sh
#  ca.org1.example.com:
#    image: hyperledger/fabric-ca:1.2.1
#    environment:
#      - FABRIC_CA_HOME=/etc/hyperledger/fabric-ca-server
#      - FABRIC_CA_SERVER_CA_NAME=ca.org1.example.com
#    ports:
#      - 7054:7054
#    command: sh -c 'fabric-ca-server start --ca.certfile /etc/hyperledger/fabric-ca-server-config/ca.org1.example.com-cert.pem --ca.keyfile /etc/hyperledger/fabric-ca-server-config/19ab65abbb04807dad12e4c0a9aaa6649e70868e3abd0217a322d89e47e1a6ae_sk -b admin:adminpw -d'
#    volumes:
#      - ./hyperledger-composer/fabric-scripts/hlfv12/composer/crypto-config/peerOrganizations/org1.example.com/ca/:/etc/hyperledger/fabric-ca-server-config
#    container_name: ca.org1.example.com
#
#  orderer.example.com:
#    container_name: orderer.example.com
#    image: hyperledger/fabric-orderer:1.2.1
#    environment:
#      - ORDERER_GENERAL_LOGLEVEL=debug
#      - ORDERER_GENERAL_LISTENADDRESS=0.0.0.0
#      - ORDERER_GENERAL_GENESISMETHOD=file
#      - ORDERER_GENERAL_GENESISFILE=/etc/hyperledger/configtx/composer-genesis.block
#      - ORDERER_GENERAL_LOCALMSPID=OrdererMSP
#      - ORDERER_GENERAL_LOCALMSPDIR=/etc/hyperledger/msp/orderer/msp
#    working_dir: /opt/gopath/src/github.com/hyperledger/fabric
#    command: orderer
#    ports:
#      - 7050:7050
#    volumes:
#        - ./hyperledger-composer/fabric-scripts/hlfv12/composer/:/etc/hyperledger/configtx
#        - ./hyperledger-composer/fabric-scripts/hlfv12/composer/crypto-config/ordererOrganizations/example.com/orderers/orderer.example.com/msp:/etc/hyperledger/msp/orderer/msp
#
#  peer0.org1.example.com:
#    container_name: peer0.org1.example.com
#    image: hyperledger/fabric-peer:1.2.1
#    environment:
#      - CORE_LOGGING_LEVEL=debug
#      - CORE_CHAINCODE_LOGGING_LEVEL=DEBUG
#      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
#      - CORE_PEER_ID=peer0.org1.example.com
#      - CORE_PEER_ADDRESS=peer0.org1.example.com:7051
#      - CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE=composer_default
#      - CORE_PEER_LOCALMSPID=Org1MSP
#      - CORE_PEER_MSPCONFIGPATH=/etc/hyperledger/peer/msp
#      - CORE_LEDGER_STATE_STATEDATABASE=CouchDB
#      - CORE_LEDGER_STATE_COUCHDBCONFIG_COUCHDBADDRESS=couchdb:5984
#    working_dir: /opt/gopath/src/github.com/hyperledger/fabric
#    entrypoint: /root/entrypoint.sh
#    ports:
#      - 7051:7051
#      - 7053:7053
#    volumes:
#        - /var/run/:/host/var/run/
#        - ./hyperledger-composer/entrypointFabricPeer.sh:/root/entrypoint.sh
#        - ./hyperledger-composer/fabric-scripts/hlfv12/composer/:/etc/hyperledger/configtx
#        - ./hyperledger-composer/fabric-scripts/hlfv12/composer/crypto-config/peerOrganizations/org1.example.com/peers/peer0.org1.example.com/msp:/etc/hyperledger/peer/msp
#        - ./hyperledger-composer/fabric-scripts/hlfv12/composer/crypto-config/peerOrganizations/org1.example.com/users:/etc/hyperledger/msp/users
#    depends_on:
#      - orderer.example.com
#      - couchdb
#
#  couchdb:
#    container_name: couchdb
#    image: hyperledger/fabric-couchdb:0.4.10
#    ports:
#      - 5984:5984
#    environment:
#      DB_URL: http://localhost:5984/member_db

volumes:
  db-data:
  network-admin-cards:
