version: '3'
services:

  web:
    build: ./frontend/
    volumes:
    - ./frontend/:/app/
    - /app/node_modules
    - /root/.npm
    ports:
    - '3000:3000'
    network_mode: host
    environment:
    - NODE_ENV=development

  backend:
    build: api/
    ports: 
    - "8090:8090"
    network_mode: host
    depends_on:
    - postgres

  postgres:
    image: postgres
    environment:
      POSTGRES_PASSWORD: mysecretpassword
      POSTGRES_USER: postgres
      POSTGRES_DB: Aktivist_Db
    volumes:
    - db-data:/var/lib/postgresql/data
    ports:
    - "5432:5432"
    network_mode: host

  blockchain:
    build: hyperledger-composer/
    ports:
    - "8080:8080"
    - "9876:9876"
    network_mode: host
    volumes:
    - ./hyperledger-composer/fabric-scripts/hlfv12/composer/crypto-config/:/hyperledger-fabric/crypto-config
    - ./hyperledger-composer/the-aktivist-network/:/hyperledger-fabric/the-aktivist-network
    - network-admin-cards:/hyperledger-fabric/admin-cards/
    - /hyperledger-fabric/node_modules
    - /root/.npm

volumes:
  db-data:
  network-admin-cards:
